import { Topic, LearningFlow } from "./types";

export const user = {
  name: "Alex",
  avatar: "",
  initials: "A",
};

export const topics: Topic[] = [
  {
    id: "concorde",
    title: "Why Concorde Failed",
    description: "A story about engineering brilliance, economics, and timing.",
    image: "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=600&q=80",
    duration: "5 min",
    cardCount: 12,
    completionCount: "1.2K",
    progress: 0,
    creator: { id: "c1", name: "Sarah Chen", avatar: "" },
  },
  {
    id: "fermi-paradox",
    title: "The Fermi Paradox",
    description: "Where is everybody? A journey through the great silence.",
    image: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&q=80",
    duration: "8 min",
    cardCount: 15,
    completionCount: "3.4K",
    progress: 33,
    timeRemaining: "5 min left",
    creator: { id: "c2", name: "Marcus Webb", avatar: "" },
  },
  {
    id: "gps",
    title: "How GPS Works",
    description: "The invisible grid that guides the world.",
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&q=80",
    duration: "6 min",
    cardCount: 10,
    completionCount: "2.1K",
    creator: { id: "c3", name: "Emily Torres", avatar: "" },
  },
  {
    id: "butterfly-effect",
    title: "The Butterfly Effect",
    description: "How small changes create enormous consequences.",
    image: "https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=600&q=80",
    duration: "4 min",
    cardCount: 8,
    completionCount: "890",
    creator: { id: "c4", name: "David Kim", avatar: "" },
  },
  {
    id: "ocean-trenches",
    title: "Deep Sea Trenches",
    description: "Exploring the deepest places on Earth.",
    image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80",
    duration: "7 min",
    cardCount: 14,
    completionCount: "560",
    creator: { id: "c5", name: "Lisa Park", avatar: "" },
  },
];

export const continuedTopics: Topic[] = [
  topics[1],
];

export const trendingTopics: Topic[] = [
  topics[0],
  topics[2],
  topics[3],
  topics[4],
  topics[1],
];

export const communityTopics: Topic[] = [
  { ...topics[3], creator: { id: "c6", name: "Jordan Lee", avatar: "" } },
  { ...topics[4], creator: { id: "c7", name: "Priya Sharma", avatar: "" } },
  { ...topics[2], creator: { id: "c8", name: "Tom Baker", avatar: "" } },
  { ...topics[0], creator: { id: "c9", name: "Anna Wolf", avatar: "" } },
];

export const mockLearningFlows: Record<string, LearningFlow> = {
  concorde: {
    topicId: "concorde",
    cards: [
      {
        id: "concorde-hook",
        type: "hook",
        title: "The **Fastest** Passenger Plane Ever Built",
        body: "For nearly three decades, Concorde crossed the Atlantic in under **3.5 hours** — less than half the time of a conventional flight. It remains one of the most ambitious engineering projects in aviation history.\n\n*Why did such a marvel fail?*",
        image: "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=800&q=80",
        imageAlt: "Concorde on runway at sunset",
      },
      {
        id: "concorde-fact",
        type: "fact",
        title: "Supersonic by Design",
        body: "Concorde cruised at **Mach 2.04** — more than twice the speed of sound. At 60,000 feet, passengers could see the *curvature of the Earth*.",
        fact: "Air friction heated the fuselage so much that the airframe expanded by **10 inches** mid-flight. The cockpit windows were too hot to touch after landing.",
        source: "British Airways Engineering Archives",
        image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800&q=80",
        imageAlt: "Concorde cockpit instruments",
      },
      {
        id: "concorde-timeline",
        type: "timeline",
        title: "The Rise and Fall of Concorde",
        body: "A brief timeline of Concorde's journey from concept to retirement:",
        events: [
          { date: "1962", label: "Anglo-French treaty signed", description: "UK and France agree to jointly develop a supersonic transport." },
          { date: "1969", label: "First test flight", description: "Concorde 001 takes off from Toulouse." },
          { date: "1976", label: "Commercial service begins", description: "Flights launch from London and Paris to Bahrain and Rio." },
          { date: "2000", label: "Air France Flight 4590 crash", description: "A tire burst leads to a catastrophic crash, killing 113." },
          { date: "2003", label: "Retirement", description: "Concorde is permanently grounded due to rising costs and falling demand." },
        ],
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80",
      },
      {
        id: "concorde-comparison",
        type: "comparison",
        title: "Concorde vs. Modern Aircraft",
        body: "The trade-off between **speed** and **efficiency** defined Concorde's fate.",
        comparisonA: "100 passengers\nMach 2.04\n$20M unit cost\n4,000 km range\n100x sonic boom",
        comparisonB: "850 passengers\nMach 0.85\n$445M unit cost\n15,000 km range\nNear-silent takeoff",
        labelA: "Concorde",
        labelB: "Airbus A380",
        image: "https://images.unsplash.com/photo-1556388158-158f3c440a63?w=800&q=80",
        imageAlt: "Concorde side profile next to A380",
      },
      {
        id: "concorde-diagram",
        type: "diagram",
        title: "The **Ogival Delta Wing**",
        body: "Concorde's wing shape was a revolutionary design that worked well at **both** subsonic and supersonic speeds.",
        diagramLabels: [
          "Leading edge: sharp for supersonic airflow",
          "Wing root: thickened for fuel storage",
          "Elevons: combined elevators and ailerons",
          "Engine nacelles: four Olympus turbojets",
        ],
        image: "https://images.unsplash.com/photo-1529074963767-98f45c47344e?w=800&q=80",
        imageAlt: "Diagram of Concorde delta wing shape",
      },
      {
        id: "concorde-prediction",
        type: "prediction",
        title: "Will Supersonic Travel Return?",
        body: "Companies like **Boom Supersonic** and **NASA** (with the X-59) are developing a new generation of supersonic aircraft. Key challenges include:\n\n- **Sonic boom** reduction technology\n- **Sustainable aviation fuel** requirements\n- **Regulatory approval** for overland flights\n\n*When do you think commercial supersonic flight will return?*",
        options: ["Within 5–10 years", "Within 10–20 years", "Not in my lifetime", "It will never return"],
        image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80",
      },
      {
        id: "concorde-poll",
        type: "poll",
        title: "What Matters Most in Air Travel?",
        body: "If you could only choose **one** priority for the future of aviation, which would it be?",
        options: [
          "Speed — get there faster",
          "Cost — make it affordable",
          "Environment — reduce emissions",
          "Comfort — improve the experience",
        ],
      },
      {
        id: "concorde-question",
        type: "question",
        title: "Check Your Understanding",
        body: "What was the **primary** reason Concorde was permanently retired in 2003?",
        options: [
          "The 2000 crash made it unsafe",
          "Unsustainable economics and operating costs",
          "Lack of passenger interest",
          "Newer planes made it obsolete",
        ],
        correctIndex: 1,
        explanation: "While the 2000 crash accelerated its decline, Concorde was retired primarily because it was no longer economically viable — maintenance costs were enormous and post-9/11 demand collapsed.",
        image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800&q=80",
      },
    ],
    quiz: {
      questions: [
        {
          id: "concorde-q1",
          question: "Why did Concorde ultimately fail as a commercial venture?",
          options: [
            "Safety regulations after the 2000 crash",
            "Lack of passenger demand from the start",
            "Unsustainable economics and high operating costs",
            "Fuel price spikes in the 1970s",
          ],
          correctIndex: 2,
          explanation: "Concorde failed due to unsustainable economics. Its per-seat operating costs were roughly 10x that of a subsonic aircraft, and post-9/11 demand made it impossible to continue.",
        },
        {
          id: "concorde-q2",
          question: "At what speed did Concorde cruise, and what unique phenomenon did passengers experience?",
          options: [
            "Mach 1.5 — visible sonic boom clouds",
            "Mach 2.04 — curvature of the Earth visible",
            "Mach 3.0 — weightlessness at peak altitude",
            "Mach 1.0 — standard subsonic cruise",
          ],
          correctIndex: 1,
          explanation: "Concorde cruised at Mach 2.04 (roughly 1,354 mph) at 60,000 feet, where passengers could see the curvature of the Earth.",
        },
        {
          id: "concorde-q3",
          question: "What type of wing did Concorde use?",
          options: ["Swept wing", "Ogival delta wing", "Conventional straight wing", "Variable-sweep wing"],
          correctIndex: 1,
          explanation: "Concorde used an ogival delta wing design — a curved delta shape optimized for efficiency at both subsonic and supersonic speeds.",
        },
        {
          id: "concorde-q4",
          question: "How much did Concorde's airframe expand during flight due to heat?",
          options: ["About 2 inches", "About 6 inches", "About 10 inches", "About 18 inches"],
          correctIndex: 2,
          explanation: "Aerodynamic heating caused the aluminum airframe to expand by up to 10 inches in flight. The cockpit windows became too hot to touch after landing.",
        },
      ],
    },
    connectedTopics: [
      {
        id: "boom-supersonic",
        title: "Boom Supersonic",
        description: "A modern startup trying to revive supersonic travel with the Overture aircraft.",
        relationship: "Concorde's modern successor",
      },
      {
        id: "aviation-economics",
        title: "Aviation Economics",
        description: "How airlines make money and why operating costs matter more than speed.",
        relationship: "The root cause of Concorde's failure",
      },
      {
        id: "sonic-boom",
        title: "Sonic Booms",
        description: "The physics of shock waves and why overland supersonic flight is banned.",
        relationship: "Key regulatory challenge for supersonic flight",
      },
      {
        id: "tu-144",
        title: "The Soviet Concorde",
        description: "The Tupolev Tu-144, the USSR's answer to Concorde.",
        relationship: "Concorde's Soviet competitor",
      },
    ],
  },

  "fermi-paradox": {
    topicId: "fermi-paradox",
    cards: [
      {
        id: "fermi-hook",
        type: "hook",
        title: "Where Is **Everybody**?",
        body: "Enrico Fermi looked up at the stars during a 1950 lunch conversation and asked a deceptively simple question: *'If the probability of alien life is so high, where is everybody?'*\n\nThis question became known as the **Fermi Paradox** — and it still has no good answer.",
        image: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&q=80",
        imageAlt: "Milky Way galaxy",
      },
      {
        id: "fermi-fact",
        type: "fact",
        title: "The Numbers Game",
        body: "Using the **Drake Equation**, scientists estimate there could be **10,000+** intelligent civilizations in our galaxy alone.",
        fact: "There are more stars in the universe than grains of sand on all of Earth's beaches — roughly **10^24** stars. If even 0.001% have intelligent life, that's still 10^19 civilizations.",
        source: "Drake Equation, SETI Institute",
        image: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=800&q=80",
        imageAlt: "Star field deep space",
      },
      {
        id: "fermi-timeline",
        type: "timeline",
        title: "A Brief History of the Search",
        body: "Humanity's search for extraterrestrial intelligence across the decades:",
        events: [
          { date: "1950", label: "Fermi asks 'Where is everybody?'", description: "The paradox is born during a casual lunch conversation at Los Alamos." },
          { date: "1961", label: "Drake Equation formulated", description: "Frank Drake creates his equation to estimate the number of detectable civilizations." },
          { date: "1977", label: "The Wow! Signal", description: "A 72-second narrowband radio signal detected at Ohio State — never repeated." },
          { date: "1995", label: "First exoplanet discovered", description: "51 Pegasi b proves that planets are common around other stars." },
          { date: "2022+", label: "JWST begins scanning exoplanet atmospheres", description: "The James Webb Space Telescope searches for biosignatures." },
        ],
        image: "https://images.unsplash.com/photo-1504333638930-c8787321eee0?w=800&q=80",
      },
      {
        id: "fermi-diagram",
        type: "diagram",
        title: "The **Great Filter**",
        body: "The Great Filter hypothesis argues that at some point between **abiogenesis** and **interstellar colonization**, there is a barrier that nearly all life fails to cross.",
        diagramLabels: [
          "Step 1: Abiogenesis (life emerges from non-life)",
          "Step 2: Prokaryotic life (simple single cells)",
          "Step 3: Complex eukaryotic life",
          "Step 4: Tool-using intelligence",
          "Step 5: Technological civilization",
          "Step 6: Interstellar colonization",
          "FILTER: The barrier could be anywhere in this chain",
        ],
        image: "https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=800&q=80",
        imageAlt: "Conceptual diagram of the Great Filter",
      },
      {
        id: "fermi-comparison",
        type: "comparison",
        title: "Optimism vs. Pessimism",
        body: "Two opposing views on the Fermi Paradox:",
        comparisonA: "Life is rare. The Great Filter is behind us — we're one of the first. The universe is empty because complex life almost never emerges.",
        comparisonB: "Civilizations self-destruct. The Great Filter is ahead — intelligence inevitably leads to extinction via war, climate collapse, or AI.",
        labelA: "Rare Earth Hypothesis",
        labelB: "Self-Destruction Hypothesis",
        image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80",
      },
      {
        id: "fermi-prediction",
        type: "prediction",
        title: "Will We Find ET in Our Lifetime?",
        body: "With **JWST** analyzing exoplanet atmospheres and **SETI** scanning millions of star systems, we may be closer than ever to an answer.\n\n**Key developments to watch:**\n- Biosignature detection (oxygen, methane in atmospheres)\n- Technosignature detection (Dyson spheres, artificial radio emissions)\n- Direct imaging of exoplanets",
        options: ["Yes, within 20 years", "Maybe, within 50 years", "Not in our lifetime", "We'll never find evidence"],
        image: "https://images.unsplash.com/photo-1462332420958-a05d1e002413?w=800&q=80",
      },
      {
        id: "fermi-poll",
        type: "poll",
        title: "Which Solution to the Fermi Paradox Do You Find Most Compelling?",
        body: "There are dozens of proposed solutions. Which one resonates most with you?",
        options: [
          "We're alone (Rare Earth)",
          "They're hiding (Zoo Hypothesis)",
          "They self-destruct (Great Filter ahead)",
          "We haven't listened long enough",
        ],
      },
      {
        id: "fermi-question",
        type: "question",
        title: "Quick Knowledge Check",
        body: "The **Great Filter** hypothesis suggests that:",
        options: [
          "Aliens are filtering our communications",
          "There is a barrier that prevents most life from reaching interstellar civilization",
          "Galaxies act as filters for radio waves",
          "The universe is being filtered by dark matter",
        ],
        correctIndex: 1,
        explanation: "The Great Filter proposes that at some stage in the development of life, there exists a barrier so difficult to cross that it prevents nearly all potential civilizations from reaching an interstellar-capable stage.",
        image: "https://images.unsplash.com/photo-1504333638930-c8787321eee0?w=800&q=80",
      },
    ],
    quiz: {
      questions: [
        {
          id: "fermi-q1",
          question: "What is the Fermi Paradox?",
          options: [
            "The contradiction between the high probability of alien life and our lack of contact",
            "The mathematical proof that aliens cannot exist",
            "The observation that all civilizations eventually go extinct",
            "The theory that Earth is a prison planet",
          ],
          correctIndex: 0,
          explanation: "The Fermi Paradox is the apparent contradiction between the high probability estimates for extraterrestrial civilizations and humanity's lack of contact with any such civilizations.",
        },
        {
          id: "fermi-q2",
          question: "What does the Great Filter hypothesis propose?",
          options: [
            "That aliens are actively filtering our radio signals",
            "That a barrier exists preventing most life from reaching interstellar capability",
            "That dark matter filters out alien signals",
            "That only Earth-like planets can support life",
          ],
          correctIndex: 1,
          explanation: "The Great Filter suggests a barrier exists somewhere in the evolution from simple life to interstellar civilization that prevents nearly all life from reaching the final stage.",
        },
        {
          id: "fermi-q3",
          question: "What was the 'Wow!' signal of 1977?",
          options: [
            "A confirmed alien transmission",
            "A 72-second radio signal never detected again",
            "The first exoplanet discovery announcement",
            "A signal from Voyager 1",
          ],
          correctIndex: 1,
          explanation: "The Wow! signal was a strong narrowband radio signal detected by the Big Ear radio telescope in 1977 that lasted 72 seconds and has never been detected again — its origin remains unknown.",
        },
        {
          id: "fermi-q4",
          question: "What tool is JWST using to search for potential alien life?",
          options: [
            "Direct imaging of alien cities",
            "Analyzing exoplanet atmospheres for biosignatures",
            "Listening for radio transmissions",
            "Looking for Dyson spheres",
          ],
          correctIndex: 1,
          explanation: "The James Webb Space Telescope analyzes exoplanet atmospheres by studying their transmission spectra, looking for biosignature gases like oxygen, methane, and water vapor.",
        },
        {
          id: "fermi-q5",
          question: "What fraction of stars in the visible universe does one estimate of the Drake Equation suggest host intelligent life?",
          options: ["1 in 10", "1 in 100", "1 in 10,000", "0 — Earth is unique"],
          correctIndex: 2,
          explanation: "Conservative Drake Equation estimates suggest roughly 1 in 10,000 to 1 in 100,000 stars might host an intelligent civilization — which would still mean thousands in our galaxy alone.",
        },
      ],
    },
    connectedTopics: [
      {
        id: "drake-equation",
        title: "The Drake Equation",
        description: "A probabilistic formula used to estimate the number of detectable extraterrestrial civilizations.",
        relationship: "The mathematical foundation for Fermi's question",
      },
      {
        id: "exoplanets",
        title: "Exoplanets",
        description: "Planets orbiting stars outside our solar system, many in the habitable zone.",
        relationship: "The target worlds for SETI",
      },
      {
        id: "seti",
        title: "SETI",
        description: "The Search for Extraterrestrial Intelligence, scanning the skies since 1960.",
        relationship: "Humanity's active search for answers",
      },
      {
        id: "rare-earth",
        title: "Rare Earth Hypothesis",
        description: "The idea that complex life is extremely rare in the universe.",
        relationship: "One solution to the Fermi Paradox",
      },
    ],
  },

  gps: {
    topicId: "gps",
    cards: [
      {
        id: "gps-hook",
        type: "hook",
        title: "You Use It **Every Day** (Probably Right Now)",
        body: "GPS powers everything from maps and ride-sharing to banking and farming. But most people have *no idea* how it actually works.\n\n**Spoiler:** It involves Einstein's theories of relativity.",
        image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80",
        imageAlt: "Satellite above Earth",
      },
      {
        id: "gps-fact",
        type: "fact",
        title: "A Constellation of **31 Satellites**",
        body: "GPS relies on a network of 31 active satellites orbiting at **20,200 km** altitude. At any given moment, your receiver can see **8–12** of them.",
        fact: "Each GPS satellite carries four atomic clocks accurate to **one second every 100,000 years**. The system costs about **$2 million per day** to operate.",
        source: "U.S. Space Force GPS Directorate",
        image: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=800&q=80",
        imageAlt: "GPS satellite in orbit",
      },
      {
        id: "gps-timeline",
        type: "timeline",
        title: "How GPS Was Built",
        body: "The development of GPS was a decades-long military project:",
        events: [
          { date: "1973", label: "Program initiated", description: "The U.S. Department of Defense merges several satellite navigation concepts into a single program called NAVSTAR." },
          { date: "1978", label: "First satellite launched", description: "The first Block I GPS satellite reaches orbit." },
          { date: "1993", label: "Initial operational capability", description: "GPS achieves 24-satellite constellation." },
          { date: "2000", label: "Selective Availability turned off", description: "President Clinton ends intentional civilian signal degradation, improving accuracy 10x overnight." },
          { date: "2020", label: "GPS III modernized", description: "New satellites with 3x better accuracy and anti-jamming capabilities." },
        ],
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
      },
      {
        id: "gps-diagram",
        type: "diagram",
        title: "Trilateration: The **Core** of GPS",
        body: "GPS works through **trilateration** — using distance measurements from three or more satellites to pinpoint your location.",
        diagramLabels: [
          "Satellite A: 'You are 20,000 km from me'",
          "Satellite B: 'You are 21,500 km from me'",
          "Satellite C: 'You are 19,800 km from me'",
          "Your position: The intersection point of all three spheres",
          "Fourth satellite: Required for time synchronization",
        ],
        image: "https://images.unsplash.com/photo-1529074963767-98f45c47344e?w=800&q=80",
        imageAlt: "GPS trilateration diagram",
      },
      {
        id: "gps-comparison",
        type: "comparison",
        title: "GPS vs. Other Navigation Systems",
        body: "The US isn't the only country with a global navigation satellite system (GNSS):",
        comparisonA: "31 satellites\n20,200 km orbit\n~3 m accuracy (civilian)\n$2M/day operating cost",
        comparisonB: "35 satellites\n23,222 km orbit\n~2 m accuracy\nCompeting global system",
        labelA: "GPS (USA)",
        labelB: "GLONASS (Russia)",
        image: "https://images.unsplash.com/photo-1556388158-158f3c440a63?w=800&q=80",
        imageAlt: "GPS vs GLONASS comparison",
      },
      {
        id: "gps-prediction",
        type: "prediction",
        title: "The Future of Navigation",
        body: "GPS is evolving with new technologies:\n\n- **L5 frequency**: New civilian signal with sub-meter accuracy\n- **Quantum navigation**: Navigation without satellites\n- **Lunar GPS**: NASA working on navigation for the Moon",
        options: ["Satellite-free by 2035", "GPS will stay dominant", "Augmented by quantum nav", "Replaced by something new"],
        image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80",
      },
      {
        id: "gps-question",
        type: "question",
        title: "GPS Knowledge Check",
        body: "How many GPS satellites are needed for a **3D position fix** (latitude, longitude, altitude)?",
        options: ["1 satellite", "2 satellites", "3 satellites", "4 satellites"],
        correctIndex: 3,
        explanation: "You need at least 4 satellites: 3 for trilateration (x, y, z) and 1 more to correct for timing errors in the receiver's less-accurate clock.",
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
      },
    ],
    quiz: {
      questions: [
        {
          id: "gps-q1",
          question: "What mathematical technique does GPS use to determine location?",
          options: ["Triangulation", "Trilateration", "Parallax", "Dead reckoning"],
          correctIndex: 1,
          explanation: "GPS uses trilateration, not triangulation. It measures distances (not angles) from multiple satellites and finds where the distance spheres intersect.",
        },
        {
          id: "gps-q2",
          question: "How many GPS satellites are needed for a full 3D position fix?",
          options: ["2", "3", "4", "6"],
          correctIndex: 2,
          explanation: "Four satellites are needed: three for spatial trilateration (x, y, z) and a fourth to correct for timing errors in the GPS receiver's clock.",
        },
        {
          id: "gps-q3",
          question: "What major GPS accuracy improvement happened in 2000?",
          options: ["New satellites were launched", "Selective Availability was turned off", "The satellite constellation was completed", "Atomic clocks were upgraded"],
          correctIndex: 1,
          explanation: "In 2000, President Clinton ordered the intentional degradation of civilian GPS signals (Selective Availability) to be turned off, improving civilian accuracy from ~100 meters to ~5 meters.",
        },
        {
          id: "gps-q4",
          question: "What makes GPS satellite clocks so precise?",
          options: ["They use quartz crystals", "They use atomic clocks accurate to 1 second per 100,000 years", "They sync to ground stations every minute", "They use pulsar timing"],
          correctIndex: 1,
          explanation: "Each GPS satellite carries four atomic clocks that are accurate to about one second every 100,000 years. This precision is essential for nanosecond-level timing.",
        },
      ],
    },
    connectedTopics: [
      {
        id: "relativity",
        title: "Einstein's Relativity",
        description: "GPS must correct for both special and general relativistic time dilation effects.",
        relationship: "GPS proves Einstein right every day",
      },
      {
        id: "glonass",
        title: "GLONASS",
        description: "Russia's global navigation satellite system, a competitor to GPS.",
        relationship: "Alternative GNSS system",
      },
      {
        id: "atomic-clocks",
        title: "Atomic Clocks",
        description: "The ultra-precise timekeeping devices that make GPS possible.",
        relationship: "The heart of the GPS system",
      },
      {
        id: "geolocation",
        title: "Geolocation Technology",
        description: "How apps use GPS, WiFi, and cell towers to determine your location.",
        relationship: "How your phone finds you",
      },
    ],
  },

  "butterfly-effect": {
    topicId: "butterfly-effect",
    cards: [
      {
        id: "butterfly-hook",
        type: "hook",
        title: "A Butterfly Flaps Its Wings in **Brazil**...",
        body: "...and sets off a tornado in Texas. This poetic idea — that tiny changes can trigger enormous consequences — captures the essence of **chaos theory**.\n\nBut the real science is even more fascinating.",
        image: "https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=800&q=80",
        imageAlt: "Butterfly on a flower",
      },
      {
        id: "butterfly-fact",
        type: "fact",
        title: "The Man Who Discovered Chaos",
        body: "In 1961, meteorologist **Edward Lorenz** was running a weather simulation when he rounded a number from **0.506127** to **0.506**. The result was a *completely different* weather prediction.",
        fact: "This 0.000127 difference in input produced a totally different forecast for just two months of simulated time. Lorenz had accidentally discovered **deterministic chaos** — systems where small changes in initial conditions lead to wildly different outcomes.",
        source: "Lorenz, 'Deterministic Nonperiodic Flow' (1963)",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80",
        imageAlt: "Weather pattern visualization",
      },
      {
        id: "butterfly-timeline",
        type: "timeline",
        title: "Chaos Theory: A Timeline",
        body: "The development of chaos theory across the 20th century:",
        events: [
          { date: "1880s", label: "Poincaré's three-body problem", description: "Henri Poincaré discovers that even a simple three-body gravitational system can produce unpredictable orbits." },
          { date: "1961", label: "Lorenz's accidental discovery", description: "Edward Lorenz finds extreme sensitivity to initial conditions in a weather model." },
          { date: "1972", label: "Butterfly Effect named", description: "Lorenz gives a talk titled 'Predictability: Does the Flap of a Butterfly's Wings in Brazil Set Off a Tornado in Texas?'" },
          { date: "1980s", label: "Fractals and chaos popularized", description: "Benoit Mandelbrot and James Gleick bring chaos theory to the public." },
          { date: "2000s+", label: "Chaos in modern science", description: "Chaos theory applied to biology, economics, climate science, and machine learning." },
        ],
        image: "https://images.unsplash.com/photo-1504333638930-c8787321eee0?w=800&q=80",
      },
      {
        id: "butterfly-comparison",
        type: "comparison",
        title: "Chaos vs. Randomness",
        body: "Chaos is **not** the same as randomness. The difference is subtle but crucial.",
        comparisonA: "Deterministic\nFollows exact mathematical rules\nAppears random but is predictable short-term\nExample: double pendulum",
        comparisonB: "Non-deterministic\nGenuinely unpredictable\nNo underlying rules\nExample: quantum decay",
        labelA: "Chaotic System",
        labelB: "Truly Random System",
        image: "https://images.unsplash.com/photo-1509225770129-f38c268c6d1e?w=800&q=80",
        imageAlt: "Chaos versus randomness visualization",
      },
      {
        id: "butterfly-prediction",
        type: "prediction",
        title: "Can We Ever Predict the Weather Perfectly?",
        body: "The Butterfly Effect places fundamental limits on weather prediction. Even with perfect computers and data, Lorenz showed that **small errors grow exponentially**.\n\n**Current forecast accuracy:**\n- 3-day forecast: ~97% as good as 1-day\n- 7-day forecast: ~80% as good as 1-day\n- 10-day forecast: barely better than climatology",
        options: ["Yes, with quantum computers", "No, the Butterfly Effect sets a hard limit", "Yes, with enough sensors", "Only for 14 days max"],
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80",
      },
      {
        id: "butterfly-question",
        type: "question",
        title: "Test Your Understanding",
        body: "The **Butterfly Effect** is the idea that:",
        options: [
          "Butterflies cause tornadoes",
          "Small differences in initial conditions can lead to vastly different outcomes",
          "All natural systems are completely random",
          "Weather can be predicted indefinitely",
        ],
        correctIndex: 1,
        explanation: "The Butterfly Effect describes sensitive dependence on initial conditions — tiny differences in a system's starting state can lead to dramatically different outcomes over time.",
      },
    ],
    quiz: {
      questions: [
        {
          id: "butterfly-q1",
          question: "How was the Butterfly Effect discovered?",
          options: [
            "By studying butterflies in Brazil",
            "By accident when Edward Lorenz rounded a number in a weather simulation",
            "By analyzing tornado formation patterns",
            "By studying the stock market",
          ],
          correctIndex: 1,
          explanation: "Lorenz accidentally discovered it in 1961 when he rounded 0.506127 to 0.506 in his weather model and got a completely different prediction — a tiny input change produced wildly different output.",
        },
        {
          id: "butterfly-q2",
          question: "What is the key difference between a chaotic system and a truly random one?",
          options: [
            "Chaotic systems are deterministic; random systems are not",
            "Chaotic systems are random; random systems are deterministic",
            "There is no difference",
            "Chaotic systems only apply to weather",
          ],
          correctIndex: 0,
          explanation: "Chaotic systems are deterministic — they follow precise mathematical rules. The unpredictability comes from extreme sensitivity to initial conditions, not from inherent randomness.",
        },
        {
          id: "butterfly-q3",
          question: "What fundamental limit does chaos theory place on weather prediction?",
          options: [
            "None, given enough computing power",
            "Predictions beyond ~10 days are inherently unreliable",
            "Only 3-day forecasts are possible",
            "Chaos makes all weather prediction impossible",
          ],
          correctIndex: 1,
          explanation: "The Butterfly Effect means small errors in initial conditions grow exponentially, fundamentally limiting useful weather prediction to about 10-14 days regardless of computing power.",
        },
      ],
    },
    connectedTopics: [
      {
        id: "fractals",
        title: "Fractals",
        description: "Infinite patterns that repeat at every scale, deeply connected to chaos theory.",
        relationship: "The visual language of chaos",
      },
      {
        id: "weather-prediction",
        title: "Weather Prediction",
        description: "How meteorologists forecast the weather using supercomputers and ensemble models.",
        relationship: "The original application of chaos theory",
      },
      {
        id: "complex-systems",
        title: "Complex Systems",
        description: "Systems where large-scale behavior emerges from many small interactions.",
        relationship: "Butterfly effects emerge everywhere",
      },
    ],
  },

  "ocean-trenches": {
    topicId: "ocean-trenches",
    cards: [
      {
        id: "ocean-hook",
        type: "hook",
        title: "We Know More About the **Moon** Than the Deep Ocean",
        body: "Over **80%** of Earth's oceans remain unmapped and unexplored. The deep sea trenches — plunging to depths that would crush a submarine like tin foil — are among the most mysterious places on our planet.\n\n*What's hiding down there?*",
        image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800&q=80",
        imageAlt: "Deep ocean water",
      },
      {
        id: "ocean-fact",
        type: "fact",
        title: "Pressure Is **Unimaginable**",
        body: "At the bottom of the Mariana Trench, the pressure is over **1,086 bars** — equivalent to having **50 jumbo jets** stacked on top of you.",
        fact: "The Mariana Trench is deeper than Mount Everest is tall. If you placed Everest in the trench, its peak would still be over 2 km underwater. Only 3 people have ever visited the Challenger Deep — compared to 12 who have walked on the Moon.",
        source: "National Oceanic and Atmospheric Administration (NOAA)",
        image: "https://images.unsplash.com/photo-1506968430777-bf7784a67f23?w=800&q=80",
        imageAlt: "Ocean depth comparison diagram",
      },
      {
        id: "ocean-timeline",
        type: "timeline",
        title: "Deep Sea Exploration Milestones",
        body: "Humanity's quest to reach the bottom of the ocean:",
        events: [
          { date: "1875", label: "Challenger expedition", description: "HMS Challenger discovers the Mariana Trench during a global oceanographic survey." },
          { date: "1960", label: "Trieste dive", description: "Jacques Piccard and Don Walsh descend to Challenger Deep in the bathyscaphe Trieste." },
          { date: "2012", label: "James Cameron's dive", description: "Film director James Cameron reaches Challenger Deep solo in the Deepsea Challenger submersible." },
          { date: "2019", label: "Victor Vescovo's dive", description: "Vescovo reaches the deepest point and discovers plastic pollution. He also dives the other four deepest trenches." },
          { date: "2020s", label: "Ongoing exploration", description: "ROVs and autonomous submersibles begin systematic mapping using multibeam sonar." },
        ],
        image: "https://images.unsplash.com/photo-1567016526105-22da7c13161a?w=800&q=80",
      },
      {
        id: "ocean-diagram",
        type: "diagram",
        title: "How **Subduction** Creates Trenches",
        body: "Oceanic trenches are formed where one tectonic plate slides beneath another in a process called **subduction**.",
        diagramLabels: [
          "Oceanic crust (dense, thin)",
          "Continental crust (buoyant, thick)",
          "Subduction zone — plate slides downward",
          "Volcanic arc forms above the subduction zone",
          "Trench — the deepest point on the seafloor",
          "Earthquake epicenters along the fault line",
        ],
        image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80",
        imageAlt: "Diagram of subduction zone and trench formation",
      },
      {
        id: "ocean-comparison",
        type: "comparison",
        title: "The Five Deepest Trenches",
        body: "The top five deepest ocean trenches on Earth:",
        comparisonA: "Mariana Trench: 10,994m\nTonga Trench: 10,882m\nPhilippine Trench: 10,540m\nKuril-Kamchatka: 10,542m\nKermadec Trench: 10,047m",
        comparisonB: "Pacific Ocean\nPacific Ocean\nPacific Ocean\nPacific Ocean\nPacific Ocean",
        labelA: "Trench & Depth",
        labelB: "Location",
        image: "https://images.unsplash.com/photo-1556388158-158f3c440a63?w=800&q=80",
        imageAlt: "Map showing deep ocean trenches",
      },
      {
        id: "ocean-prediction",
        type: "prediction",
        title: "What Will We Find Next?",
        body: "With new technology like **ROVs**, **AUVs**, and **satellite bathymetry**, we're discovering new species and features every year.\n\n**Recent surprises:**\n- *Etmopterus benchleyi* — the ninja lanternshark (bio-luminescent)\n- *Xenophyophores* — single-celled organisms the size of a fist\n- Plastic fibers in the bodies of trench creatures (already contaminated)",
        options: ["Entirely new ecosystems", "New extremophile species", "More plastic pollution", "Ancient shipwrecks"],
        image: "https://images.unsplash.com/photo-1564053489984-3175f00e0c46?w=800&q=80",
      },
      {
        id: "ocean-poll",
        type: "poll",
        title: "Should Ocean Exploration Be Prioritized Over Space?",
        body: "We spend billions on space while the deep ocean remains largely unknown. Where should funding go?",
        options: [
          "Ocean — more relevant to Earth's future",
          "Space — the ultimate frontier",
          "Both equally",
          "Neither — solve problems on land first",
        ],
      },
      {
        id: "ocean-question",
        type: "question",
        title: "Quick Deep-Sea Check",
        body: "What process creates ocean trenches?",
        options: [
          "Volcanic eruption",
          "Plate subduction — one plate sliding under another",
          "Sea level rise over millions of years",
          "Erosion by deep ocean currents",
        ],
        correctIndex: 1,
        explanation: "Oceanic trenches are formed by subduction — where one tectonic plate slides beneath another into the mantle. This creates a deep linear depression on the seafloor.",
        image: "https://images.unsplash.com/photo-1506968430777-bf7784a67f23?w=800&q=80",
      },
    ],
    quiz: {
      questions: [
        {
          id: "ocean-q1",
          question: "How deep is the Mariana Trench's deepest point (Challenger Deep)?",
          options: [
            "About 6,000 meters",
            "About 8,000 meters",
            "About 11,000 meters",
            "About 14,000 meters",
          ],
          correctIndex: 2,
          explanation: "The Challenger Deep in the Mariana Trench reaches approximately 10,994 meters (about 11 km) below sea level — deeper than Mount Everest is tall.",
        },
        {
          id: "ocean-q2",
          question: "What process creates ocean trenches?",
          options: [
            "Volcanic eruptions on the seafloor",
            "Tectonic subduction — one plate sliding under another",
            "Erosion from deep-sea currents over millions of years",
            "Meteor impacts on the ocean floor",
          ],
          correctIndex: 1,
          explanation: "Ocean trenches are formed at subduction zones where one tectonic plate is forced beneath another into the Earth's mantle, creating a deep linear depression.",
        },
        {
          id: "ocean-q3",
          question: "What famous person visited Challenger Deep solo in 2012?",
          options: [
            "Richard Branson",
            "James Cameron",
            "Jacques Cousteau",
            "Victor Vescovo",
          ],
          correctIndex: 1,
          explanation: "Film director James Cameron descended solo to Challenger Deep in 2012 aboard the Deepsea Challenger submersible — the first solo dive and only the third visit ever.",
        },
        {
          id: "ocean-q4",
          question: "How many people have visited Challenger Deep compared to the Moon?",
          options: [
            "More have visited the deep than the Moon",
            "About the same number",
            "More have walked on the Moon",
            "Nobody has visited Challenger Deep since 1960",
          ],
          correctIndex: 2,
          explanation: "Only 3 people have ever visited Challenger Deep (1960 Trieste dive, 2012 James Cameron) while 12 people have walked on the Moon — we've explored less of our own ocean floor.",
        },
        {
          id: "ocean-q5",
          question: "What surprising thing was found in the deepest ocean trenches in 2019?",
          options: [
            "Ancient ruins",
            "Plastic pollution",
            "Active volcanoes",
            "Unknown shipwrecks",
          ],
          correctIndex: 1,
          explanation: "In 2019, Victor Vescovo's expedition found plastic fibers and debris at the bottom of the Mariana Trench — showing that human pollution has reached even the deepest parts of the ocean.",
        },
      ],
    },
    connectedTopics: [
      {
        id: "plate-tectonics",
        title: "Plate Tectonics",
        description: "The theory explaining how Earth's lithosphere moves and reshapes the planet.",
        relationship: "The force that creates trenches",
      },
      {
        id: "extremophiles",
        title: "Extremophiles",
        description: "Life forms that thrive in extreme environments like deep sea vents and trenches.",
        relationship: "Life in the deep",
      },
      {
        id: "sonar-mapping",
        title: "Sonar Mapping",
        description: "The technology used to map the ocean floor using sound waves.",
        relationship: "How we see the unseen",
      },
      {
        id: "ocean-ecosystems",
        title: "Deep Sea Ecosystems",
        description: "Unique ecosystems that survive without sunlight in the deep ocean.",
        relationship: "What lives in the trenches",
      },
    ],
  },
};

export function getMockFlow(topicId: string): LearningFlow | undefined {
  return mockLearningFlows[topicId];
}
